// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMShVdGPISBqUvl6TlG3JQMhiuXV8QRQ',
    appId: '1:301108390257:web:2076cda848d2b7396a2ed0',
    messagingSenderId: '301108390257',
    projectId: 'land-licence-system',
    authDomain: 'land-licence-system.firebaseapp.com',
    storageBucket: 'land-licence-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhG7OkFFkb1TzqLAiaeGJR2qxzR9oA1kE',
    appId: '1:301108390257:android:27ad957b3ebb81986a2ed0',
    messagingSenderId: '301108390257',
    projectId: 'land-licence-system',
    storageBucket: 'land-licence-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOspoYHXHlX-gjnyAoVWKDjfOR54pQR84',
    appId: '1:301108390257:ios:905669a95b1fa9116a2ed0',
    messagingSenderId: '301108390257',
    projectId: 'land-licence-system',
    storageBucket: 'land-licence-system.appspot.com',
    iosClientId: '301108390257-jnsuag8q9404jrferhok2n4mb40g7c7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.landLicense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOspoYHXHlX-gjnyAoVWKDjfOR54pQR84',
    appId: '1:301108390257:ios:681ea71a847095396a2ed0',
    messagingSenderId: '301108390257',
    projectId: 'land-licence-system',
    storageBucket: 'land-licence-system.appspot.com',
    iosClientId: '301108390257-vv0qvkhqqbofcrknmd4mn652le5jvmud.apps.googleusercontent.com',
    iosBundleId: 'com.example.landLicense.RunnerTests',
  );
}
